services:
  # API service
  - type: web
    name: phishguard-api
    env: python
    buildCommand: pip install -r requirements.txt && python -c "import nltk; nltk.download('stopwords')"
    startCommand: gunicorn wsgi:app
    envVars:
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
    autoDeploy: true